In [2]:
import os, sys, platform, yaml, re
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import DoubleType, FloatType, StringType
from pyspark.sql.dataframe import DataFrame
import pandas as pd
from py2neo import Graph
from pathlib import Path
import matplotlib.pyplot as plt

In [3]:
conf_path = str(Path.cwd() / "config" / "ETL_config.yaml")
with open(conf_path, "r") as f:
    CFG = yaml.safe_load(f)
    
NEO4J_URI  = CFG["neo4j"]["uri"]          # "bolt://localhost:7687"
NEO4J_USER = CFG["neo4j"]["user"]
NEO4J_PASS = CFG["neo4j"]["pass"]
NEO4J_DB   = CFG["neo4j"]["database"]

opts = {
    "url": NEO4J_URI,
    "authentication.type": "basic",
    "authentication.basic.username": NEO4J_USER,
    "authentication.basic.password": NEO4J_PASS,
    "database": NEO4J_DB,
}

In [5]:
graph = Graph(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASS), name=NEO4J_DB)

# Features temporales

In [6]:
query = """
MATCH (n)
UNWIND keys(n) AS k
RETURN k AS property_key, count(*) AS nodes_with_key
ORDER BY nodes_with_key DESC, property_key
"""

df_props = graph.run(query).to_data_frame()
df_props.head(20)

       property_key  nodes_with_key
0    account_number          855460
1         closeness          855460
2   current_balance          855460
3       eigenvector          855460
4        first_seen          855460
5             kcore          855460
6         last_seen          855460
7               lcc          855460
8          location          855460
9        louvain_id          855460
10         pagerank          855460
11           scc_id          855460
12           wcc_id          855460

In [7]:
query = """
MATCH ()-[r]->()
UNWIND keys(r) AS k
RETURN k AS property_key, count(*) AS rels_with_key
ORDER BY rels_with_key DESC, property_key
"""
df_rel_props = graph.run(query).to_data_frame()
df_rel_props.head(20)

          property_key  rels_with_key
0               amount        9504852
1    dst_balance_after        9504852
2   dst_balance_before        9504852
3         dst_currency        9504852
4            dst_delta        9504852
5              dst_seq        9504852
6                   id        9504852
7        is_laundering        9504852
8      laundering_type        9504852
9               masked        9504852
10    payment_currency        9504852
11        payment_type        9504852
12   received_currency        9504852
13   src_balance_after        9504852
14  src_balance_before        9504852
15        src_currency        9504852
16           src_delta        9504852
17             src_seq        9504852
18           timestamp        9504852